'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceReference1
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="InserUser", [Namespace]:="http://schemas.datacontract.org/2004/07/WcfService1"),  _
     System.SerializableAttribute()>  _
    Partial Public Class InserUser
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NameField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Email() As String
            Get
                Return Me.EmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailField, value) <> true) Then
                    Me.EmailField = value
                    Me.RaisePropertyChanged("Email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="gettestdata", [Namespace]:="http://schemas.datacontract.org/2004/07/WcfService1"),  _
     System.SerializableAttribute()>  _
    Partial Public Class gettestdata
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private usertabField As System.Data.DataTable
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property usertab() As System.Data.DataTable
            Get
                Return Me.usertabField
            End Get
            Set
                If (Object.ReferenceEquals(Me.usertabField, value) <> true) Then
                    Me.usertabField = value
                    Me.RaisePropertyChanged("usertab")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UpdateUser", [Namespace]:="http://schemas.datacontract.org/2004/07/WcfService1"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UpdateUser
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UIDField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Email() As String
            Get
                Return Me.EmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailField, value) <> true) Then
                    Me.EmailField = value
                    Me.RaisePropertyChanged("Email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UID() As Integer
            Get
                Return Me.UIDField
            End Get
            Set
                If (Me.UIDField.Equals(value) <> true) Then
                    Me.UIDField = value
                    Me.RaisePropertyChanged("UID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DeleteUser", [Namespace]:="http://schemas.datacontract.org/2004/07/WcfService1"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DeleteUser
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UIDField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UID() As Integer
            Get
                Return Me.UIDField
            End Get
            Set
                If (Me.UIDField.Equals(value) <> true) Then
                    Me.UIDField = value
                    Me.RaisePropertyChanged("UID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.IService1")>  _
    Public Interface IService1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/Insert", ReplyAction:="http://tempuri.org/IService1/InsertResponse")>  _
        Function Insert(ByVal user As ServiceReference1.InserUser) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/Insert", ReplyAction:="http://tempuri.org/IService1/InsertResponse")>  _
        Function InsertAsync(ByVal user As ServiceReference1.InserUser) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetInfo", ReplyAction:="http://tempuri.org/IService1/GetInfoResponse")>  _
        Function GetInfo() As ServiceReference1.gettestdata
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetInfo", ReplyAction:="http://tempuri.org/IService1/GetInfoResponse")>  _
        Function GetInfoAsync() As System.Threading.Tasks.Task(Of ServiceReference1.gettestdata)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/Update", ReplyAction:="http://tempuri.org/IService1/UpdateResponse")>  _
        Function Update(ByVal u As ServiceReference1.UpdateUser) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/Update", ReplyAction:="http://tempuri.org/IService1/UpdateResponse")>  _
        Function UpdateAsync(ByVal u As ServiceReference1.UpdateUser) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/Delete", ReplyAction:="http://tempuri.org/IService1/DeleteResponse")>  _
        Function Delete(ByVal d As ServiceReference1.DeleteUser) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/Delete", ReplyAction:="http://tempuri.org/IService1/DeleteResponse")>  _
        Function DeleteAsync(ByVal d As ServiceReference1.DeleteUser) As System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IService1Channel
        Inherits ServiceReference1.IService1, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Service1Client
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.IService1)
        Implements ServiceReference1.IService1
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Insert(ByVal user As ServiceReference1.InserUser) As String Implements ServiceReference1.IService1.Insert
            Return MyBase.Channel.Insert(user)
        End Function
        
        Public Function InsertAsync(ByVal user As ServiceReference1.InserUser) As System.Threading.Tasks.Task(Of String) Implements ServiceReference1.IService1.InsertAsync
            Return MyBase.Channel.InsertAsync(user)
        End Function
        
        Public Function GetInfo() As ServiceReference1.gettestdata Implements ServiceReference1.IService1.GetInfo
            Return MyBase.Channel.GetInfo
        End Function
        
        Public Function GetInfoAsync() As System.Threading.Tasks.Task(Of ServiceReference1.gettestdata) Implements ServiceReference1.IService1.GetInfoAsync
            Return MyBase.Channel.GetInfoAsync
        End Function
        
        Public Function Update(ByVal u As ServiceReference1.UpdateUser) As String Implements ServiceReference1.IService1.Update
            Return MyBase.Channel.Update(u)
        End Function
        
        Public Function UpdateAsync(ByVal u As ServiceReference1.UpdateUser) As System.Threading.Tasks.Task(Of String) Implements ServiceReference1.IService1.UpdateAsync
            Return MyBase.Channel.UpdateAsync(u)
        End Function
        
        Public Function Delete(ByVal d As ServiceReference1.DeleteUser) As String Implements ServiceReference1.IService1.Delete
            Return MyBase.Channel.Delete(d)
        End Function
        
        Public Function DeleteAsync(ByVal d As ServiceReference1.DeleteUser) As System.Threading.Tasks.Task(Of String) Implements ServiceReference1.IService1.DeleteAsync
            Return MyBase.Channel.DeleteAsync(d)
        End Function
    End Class
End Namespace
